# Generated by Django 2.1.1 on 2018-09-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemodel',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
