# Generated by Django 2.1.1 on 2018-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfb', '0003_placemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemodel',
            name='max_age',
            field=models.IntegerField(default=18, verbose_name='Max age to access this location'),
        ),
        migrations.AlterField(
            model_name='placemodel',
            name='min_age',
            field=models.IntegerField(default=12, verbose_name='Min age to access this location'),
        ),
    ]
