# Generated by Django 2.1.1 on 2018-09-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfb', '0004_auto_20180923_0153'),
        ('wfb', '0004_auto_20180922_1857'),
    ]

    operations = [
    ]
